### ISSUE TITLE
ImportError: cannot import name '_get_venv_sitepackages'

### ISSUE THREAD

**Issue by mrafcho001** [zchee/deoplete-jedi#152] opened 2018-02-20 23:11 UTC
# Problem summary
Deoplete crashes as soon as I go into insert mode. From logs it looks like deoplete-jedi cannot start properly due to the import error in the title. Latest deoplete, deoplete-jedi, jedi.

``` 
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 34, i
n completion_work
    filename, options)
  File "/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 542,
in completions
    stream_write(self._server.stdin, args)
  File "/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 109,
in stream_write
    pipe.flush()
BrokenPipeError: [Errno 32] Broken pipe

```

The deoplete logs show this:

```
2018-02-20 14:57:38,510 DEBUG    (deoplete.jedi.server) Starting server.  sys.path = ['/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi', '/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/
↳deoplete/vendored/parso', '/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi', '/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources', '/usr2/username/nvim_venv/nvim3/lib64/python36.
↳zip', '/usr2/username/nvim_venv/nvim3/lib64/python3.6', '/usr2/username/nvim_venv/nvim3/lib64/python3.6/lib-dynload', '/usr/lib64/python3.6', '/usr/lib/python3.6', '/usr2/username/nvim_venv/nvim3/lib/python3.6/site-packages']
2018-02-20 14:57:38,510 ERROR    (deoplete.jedi.server) Server Exception.  Shutting down.
Traceback (most recent call last):
  File "/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 224, in run
    self._loop()
  File "/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 158, in _loop
    from jedi.evaluate.sys_path import _get_venv_sitepackages
ImportError: cannot import name '_get_venv_sitepackages'
2018-02-20 14:57:38,512 DEBUG    [4799] (deoplete.jedi.worker) Started worker: <Worker(Thread-1, started 140598781093632)>
2018-02-20 14:57:38,778 DEBUG    (deoplete.jedi.server) Starting server.  sys.path = ['/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi', '/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/
↳deoplete/vendored/parso', '/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi', '/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources', '/usr2/username/nvim_venv/nvim3/lib64/python36.
↳zip', '/usr2/username/nvim_venv/nvim3/lib64/python3.6', '/usr2/username/nvim_venv/nvim3/lib64/python3.6/lib-dynload', '/usr/lib64/python3.6', '/usr/lib/python3.6', '/usr2/username/nvim_venv/nvim3/lib/python3.6/site-packages']
2018-02-20 14:57:38,778 ERROR    (deoplete.jedi.server) Server Exception.  Shutting down.
Traceback (most recent call last):
  File "/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 224, in run
    self._loop()
  File "/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 158, in _loop
    from jedi.evaluate.sys_path import _get_venv_sitepackages
ImportError: cannot import name '_get_venv_sitepackages'
2018-02-20 14:57:38,779 DEBUG    [4799] (deoplete.jedi.worker) Started worker: <Worker(Thread-2, started 140598772700928)>
2018-02-20 14:57:38,779 DEBUG    [4799] (deoplete.jedi.cache) Starting reaper thread
2018-02-20 14:57:38,780 DEBUG    [4799] (deoplete.child) on_event: Source: jedi
2018-02-20 14:57:38,780 DEBUG    [4799] (deoplete.child) main_loop: end
2018-02-20 14:57:41,311 DEBUG    [4797] (deoplete.core) completion_begin:         self.
2018-02-20 14:57:41,312 DEBUG    [4799] (deoplete.child) _read: 3277 bytes
2018-02-20 14:57:41,313 DEBUG    [4799] (deoplete.child) main_loop: merge_results begin
2018-02-20 14:57:41,313 DEBUG    [4799] (deoplete.child) merged_results: begin
2018-02-20 14:57:41,318 DEBUG    [4799] (deoplete.jedi.worker.Thread-1) Got work
2018-02-20 14:57:41,323 WARNING  [4799] (deoplete.jedi.worker.Thread-1) Restarting server because it's taking too long
2018-02-20 14:57:41,323 DEBUG    [4799] (deoplete.jedi.worker.Thread-1) Worker error
Traceback (most recent call last):
  File "/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/worker.py", line 71, in run
    self._client.restart()
  File "/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 516, in restart
    self.shutdown()
  File "/usr2/username/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py", line 507, in shutdown
    self._server.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
```

## Expected
Not crashing

## Environment Information

 * OS: Centos 7.3
 * Neovim version: v0.2.3-454-g8fc437ef4

## Provide a minimal init.vim with less than 50 lines (required)

```vim
let g:python3_host_prog = '/usr2/username/nvim_venv/nvim3/bin/python'

set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')

let g:deoplete#sources#jedi#python_path = '/usr2/username/nvim_venv/nvim3/bin/python'
let g:deoplete#sources#jedi#debug_server = 1
```

**Comment by Shougo** [comment] 2018-02-21 02:04
I cannot reproduce the problem.
But current latest jedi has not `_get_venv_sitepackages`.

@blueyed Ping.

I think deoplete-jedi should upgrade for the latest jedi.

**Comment by Shougo** [comment] 2018-02-21 02:06
https://github.com/zchee/deoplete-jedi/pull/131

Current jedi is 0.11.0.
And 0.11.1 is already released in December.

**Comment by blueyed** [comment] 2018-02-21 20:55
@mrafcho001 
Is your Git submodule at `./deoplete-jedi/rplugin/python3/deoplete/vendored/jedi` at `dd924a2`?
Looks like you might be using a later jedi version - but it should come from deoplete-jedi's submodule.

**Comment by mrafcho001** [comment] 2018-02-21 21:44
For some reason the submodules were checked out to the latest commit. I deleted `deoplete` and `deoplete-jedi` plugins and installed them again with `vim-plugged`, something that I've tried several times before. This time the submodules were checked out to the expected commits.

I had previous installed `jedi` with `pip` into the neovim3 venv, which I've now removed. I'm not sure if `deoplete-jedi` was attempting to use the `pip install`ed version instead of the `deoplete-jedi` version.

Either way, after correctly checking out the plugins, everything appears to work as expected. I guess we can chalk this up to `vim-plugged` incorrectly checking out `deoplete-jedi` and possibly having `jedi` installed in the python venv.

Really appreciate your help, @Shougo @blueyed

**Comment by blueyed** [comment] 2018-02-21 23:42
@mrafcho001 
Would be nice to ensure that it is really a problem with vim-plug only, i.e. that deoplete-jedi uses its vendored jedi submodule.  This should get ensured by setting PYTHONPATH here: https://github.com/zchee/deoplete-jedi/blob/8c41d9d8d5dcb0381b51bd22ddb0bee7ee3869c2/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L474.

But then vim-plug's handling of submodules also seems sane: https://github.com/junegunn/vim-plug/blob/96375cb7d30b7caf2a9417799ff509b59b43a627/plug.vim#L1099-L1103.

Apart from that I think the error reporting could be better: you should have seen a message about the server failing to start with its exception there already, instead of in the logs.  I am looking into this now.

**Comment by Shougo** [comment] 2018-02-22 02:08
Oh, Wow...

**Comment by Shougo** [comment] 2018-02-22 02:11
dein.vim has the same routine(`git submodule update --init --recursive`).
But dein.vim has not the problem...

**Closed** 2018-02-22 02:10 UTC
