### ISSUE TITLE
deoplete-jedi does show proper module completions on import statements like "from x.y"

### ISSUE THREAD

**Issue by zabulazza** [zchee/deoplete-jedi#191] opened 2018-08-03 20:05 UTC
# Problem summary
Deoplete-jedi shows list of all modules on completions like 'from x.y'. Please see [example.](https://imgur.com/GD6n5zZ)

## Expected
Deoplete-jedi shows completion only for proper modules

## Environment Information

 * OS: OSX (also reproduced on Ubuntu 16.04) 
 * Neovim version: 0.2.2

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Use the following as a template.
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.

## Steps to reproduce the issue after starting Neovim (required)

 1. Open python file
 2. Start typing import as "from tensorflow."

## Screen shot (if possible)
Provided in summary

## Upload the logfile(s)
https://pastebin.com/yQAT9VX2 - deoplete log

**Comment by Shougo** [comment] 2018-08-06 02:29
Reproduced.   But it is hard to fix for me.

@blueyed Ping.  Can you fix the problem?
I think module completion is broken.

**Comment by zabulazza** [comment] 2018-08-08 19:35
@Shougo, thank you very much for your help! 

By the way, looks like [[RFC] Update Jedi PR](https://github.com/zchee/deoplete-jedi/pull/179#issuecomment-410571499) fixes this issue - I've tried to reproduce this fix by myself and issue with broken completions disappeared. Hope this will help.

**Comment by zabulazza** [comment] 2018-08-10 13:30
@Shougo , could you please reopen this issue? Looks like it still persists after update.

However, I was able to overcome this by updating  ```rplugin/python3/deoplete/sources/deoplete_jedi/server.py``` as per [Update Jedi RFC](https://github.com/zchee/deoplete-jedi/pull/179)

**Comment by blueyed** [comment] 2018-08-10 13:36
@zabulazza 

> However, I was able to overcome this by updating rplugin/python3/deoplete/sources/deoplete_jedi/server.py as per Update Jedi RFC

Please elaborate.. this PR is merged, i.e. `server.py` should be the same as from there already in master?!

**Comment by blueyed** [comment] 2018-08-10 13:37
So maybe you only have to run `git submodule update --recursive`?

**Comment by zabulazza** [comment] 2018-08-10 19:03
@blueyed, excuse me for confusing you - my previous statement was unclear.

Ok, so basically I had following situation - I have only reproduced fix for ```server.py``` (without submodules update) before update deoplete-jedi to last version and everything worked as expected. However, issue with incorrect list of completions still persists after update (even after ```git submodule update --recursive```).

Please, let me know in case if I can help you somehow or if I need provide you an additional information , because I am really interested in this plugin working.

**Comment by blueyed** [comment] 2018-08-10 20:58
@zabulazza 
Then you might want to help debugging/fixing it yourself.. :)

I am not using deoplete/deoplete-jedi by default myself currently, but rather jedi-vim and only enable deoplete manually.. it is too much overhead and subtle bugs for me.

My last WIP for deoplete-jedi was to use Jedi more directly (https://github.com/zchee/deoplete-jedi/pull/184), but I think it needs the caching still (because deoplete is calling it so often).

I suggest:

1. trying if updating the submodules to latest jedi/parso helps for deoplete-jedi already.
2. otherwise you could try if jedi-vim (use its `Ctrl-x Ctrl-o`) shows the same issue.
3. try https://github.com/zchee/deoplete-jedi/pull/184 (and maybe up the submodules in there, too).

**Comment by Shougo** [comment] 2018-08-13 23:18
OK.  Reopened.

**Comment by Shougo** [comment] 2018-08-16 23:45
#184 fixes it.

**Closed** 2018-09-15 10:43 UTC
Labels: bug
