### ISSUE TITLE
Setting up Python for Neovim

### ISSUE THREAD

**Issue by amirelemam** [zchee/deoplete-jedi#98] opened 2017-01-06 02:56 UTC
# Problem summary
Unable to activate neovim on pyenv

## Expected
When running the code to activate neovim on pyenv, "virtualenv"  and "activate" are not recognized as valid pyenv commands.

## Environment Information

 * OS: Mac OS 10.11
 * Neovim version: 0.1.7

## Provide a minimal init.vim with less than 50 lines (required)

```vim
" Use the following as a template.
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.

## Steps to reproduce the issue after starting Neovim (required)

1. pyenv install 2.7.12
2. pyenv install 3.6.0
3. pyenv virtualenv 2.7.12 neovim2
4. pyenv virtualenv 3.6.0 neovim3
5. pyenv activate neovim2
6. pip install neovim
7. pyenv which python  # Note the path
8. pyenv activate neovim3
9. pip install neovim
10. pyenv which python  # Note the path

**Comment by meiralins** [comment] 2017-01-06 22:58
Updating Jedi solved the issue for me.

But the [python-client](https://github.com/neovim/python-client/) broke for me with version 3.6.
You can install pyuv version 0.10.x in the same virtualenv as a provisional fix.
I sent a [PR](https://github.com/neovim/python-client/pull/240) to fix for pyuv >1.0.

I will see if I can fix for bare asyncio.

**Comment by amirelemam** [comment] 2017-01-08 03:22
Thanks. Installing pyuv 0.10 solved the problem.

2017-01-06 20:58 GMT-02:00 Hélio Meira Lins <notifications@github.com>:

**Comment by blueyed** [comment] 2017-01-08 12:43
What exactly is the issue here?

It seems like completion just does not happen when using Python 3.6, but without any error?

We should ensure that the error that prevents this does not get swallowed then probably, too!

**Comment by blueyed** [comment] 2017-01-08 12:45
Closing as dupe of #100.

**Closed by blueyed** 2017-01-08 12:45 UTC
