### ISSUE TITLE
deoplete-jedi processes are running even if I edit non-py file

### ISSUE THREAD

**Issue by rafi** [zchee/deoplete-jedi#59] opened 2016-09-18 17:16 UTC
# Problems summary
I've noticed that deoplete-jedi is running 8 processes and consuming CPU even if I opened and editing a non-python related file.

## Expected
deoplete-jedi processes running only when there is work to do.

## Environment Information
 * OS: OSX El Capitan 10.11.6
 * Neovim version: v0.1.6-119-g7b6786f
 * tmux 2.2

## Provide a minimal init.vim with less than 50 lines (Required!)
```vim
if &compatible
	set nocompatible
endif

" Set configuration paths
let s:cfg_dir = $HOME.'/.config/nvim'
let s:venv_dir = $HOME.'/.cache/nvim/venv'

let s:bundle_dir = s:cfg_dir.'/bundle'
let s:dein_dir = s:bundle_dir.'/repos/github.com/Shougo/dein.vim'
let g:python_host_prog = s:venv_dir.'/neovim2/bin/python'
let g:python3_host_prog = s:venv_dir.'/neovim3/bin/python'

" Install dein.vim
if ! isdirectory(s:dein_dir)
	execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
endif
execute 'set runtimepath+='.substitute(
	\ fnamemodify(s:dein_dir, ':p') , '/$', '', '')

" Add plugins to bundle
call dein#begin(s:bundle_dir, [ expand('<sfile>') ])
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/deoplete.nvim')
call dein#add('zchee/deoplete-jedi')
call dein#end()

" Install any missing plugins
if dein#check_install()
	call dein#install()
endif

" Enable highlight syntax
filetype plugin indent on
syntax enable

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)
 1. Run `nvim ~/.bashrc`
 2. Enter 'insert' mode
 3. On different terminal, run `ps -ef | grep deoplete` or `pstree -pl -s deoplete`

 Repeat steps 1-3 in a different terminal and see processes _doubling_.

## Generate a logfile if appropriate
N/A

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/147918/18617627/a2dc4792-7ddc-11e6-8563-63195ed3ecb9.png)

## Upload the log file
N/A

**Comment by blueyed** [comment] 2016-09-18 20:53
FWIW: I've tried to get remote_pdb into this, but failed: https://github.com/ionelmc/python-remote-pdb.

It would be nice to trigger this through SIGUSR to see what is going on.

**Comment by Shougo** [comment] 2016-09-19 07:50
I have tested it.  But I cannot reproduce it.
deoplete-jedi processes are generated after editing Python script.

**Comment by blueyed** [comment] 2016-09-20 22:44
@Shougo 
Are you sure?  (were you tricked by `let g:deoplete#enable_at_startup = 1` not being run directly)

```vim
set rtp+=~/.vim/neobundles/deoplete
set rtp+=~/.vim/neobundles/deoplete-jedi
let g:deoplete#enable_at_startup = 1
```

Run `:exe '!pstree -apl' getpid()`:

```
nvim,27759 -u vimrc.minimal
  |-pstree,27849 -apl 27759
  |-python3,27795 -c import sys; sys.path.remove(""); import neovim; neovim.start_host() /home/user/.vim/neobundles/deoplete/rplugin/python3/deoplete
  |   `-python,27831 -u /home/user/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py --desc-length 0 --debug
  `-{nvim},27832
```

I've looked into this / https://github.com/Shougo/deoplete.nvim/issues/336, and not starting deoplete-jedi always would be very nice to have in general already.

**Comment by zchee** [comment] 2016-09-21 02:05
@rafi reproduced. re-opened.
Sorry.

**Comment by zchee** [comment] 2016-09-21 02:08
@rafi @blueyed It's a bug.
But @Shougo said will fix on deoplete.nvim sources side.
Please wait for the update of deoplete.nvim.

@Shougo Thanks for follow up.

**Comment by rafi** [comment] 2016-09-21 20:26
@zchee @Shougo I have updated the minimal init.vim to reproduce in the description above.

**Comment by Shougo** [comment] 2016-09-22 05:43
It is fixed in the latest deoplete.

**Closed by Shougo** 2016-09-22 05:43 UTC
Labels: cannot reproduce
